#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
  path: /auth
  methods: ['POST']

gesdinet_jwt_refresh_token:
    path:     /refresh-token
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

coop_tilleuls_forgot_password:
    resource: '@CoopTilleulsForgotPasswordBundle/Resources/config/routing.xml'
    prefix:   '/forgot_password'